#!/usr/bin/env bash

set -eu

SIMDIR="simul"
GHDLFLAGS="--ieee=standard -fsynopsys --warn-no-vital-generic --workdir=$SIMDIR"

COMPONENT=$1
SUBCOMPONENT=$2

SRCFILES="src/$COMPONENT/$SUBCOMPONENT.vhdl"

mkdir -p $SIMDIR
ghdl -i $GHDLFLAGS --work=work testbench/$COMPONENT/$SUBCOMPONENT"_tb.vhdl" $SRCFILES
ghdl -m $GHDLFLAGS --work=work $SUBCOMPONENT"_tb"
