#!/usr/bin/env bash

set -eu

COMPONENT=$1
SUBCOMPONENT=$2

if [[ "$SUBCOMPONENT" == "main" ]]; then
	FILE=$3
	./scripts/generate-tb.py $COMPONENT $FILE
fi

./scripts/compile $COMPONENT $SUBCOMPONENT
./scripts/simul $SUBCOMPONENT
