#!/usr/bin/env bash

set -eu

SIMDIR="simul"
GHDLFLAGS="--ieee=standard -fsynopsys --warn-no-vital-generic --workdir=$SIMDIR"

COMPONENT="multiplier"

UTILS="testbench/utils/*"
SRCFILES="src/$COMPONENT/* src/result_builder.vhdl"

mkdir -p $SIMDIR
ghdl -i $GHDLFLAGS --work=work testbench/$COMPONENT/"fm_tb.vhdl" $UTILS $SRCFILES
ghdl -m $GHDLFLAGS --work=work "fm_tb"
